language: node_js
services:
  - docker

before_install:
  - docker build -t mkorneyc/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mkorneyc/react-test npm run test

after_success:
  - docker build -t mkorneyc/multi-client ./client
  - docker build -t mkorneyc/multi-nginx ./nginx
  - docker build -t mkorneyc/multi-server ./server
  - docker build -t mkorneyc/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push mkorneyc/multi-client
  - docker push mkorneyc/multi-nginx
  - docker push mkorneyc/multi-server
  - docker push mkorneyc/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-110525979287
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
    
    
